version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://labrat-vm:3001/api}

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - type: bind
        source: ./server/database
        target: /app/database
        read_only: false
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001 