version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://labrat-vm:3001/api}

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - db_data:/app/database
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001
    user: node

volumes:
  db_data:
    name: motora_db_data
    driver: local 