#!/bin/bash

# Base URL for the API
API_URL="https://103.150.190.62/api"

# Function to insert a motorcycle
insert_motorcycle() {
    local manufacturer="$1"
    local model="$2"
    
    curl -k -X POST "${API_URL}/motorcycles" \
        -H "Content-Type: application/json" \
        -d "{\"manufacturer\":\"${manufacturer}\",\"model\":\"${model}\"}"
    
    echo # Add a newline for better readability
}

echo "Inserting Matic (Automatic) Motorcycles..."
# Matic Motorcycles
insert_motorcycle "Honda" "BeAT FI CBS K25"
insert_motorcycle "Honda" "BeAT FI K25"
insert_motorcycle "Honda" "BeAT Karburator KVY"
insert_motorcycle "Honda" "BeAT POP eSP K61"
insert_motorcycle "Honda" "BeAT Sporty eSP K25G"
insert_motorcycle "Honda" "BeAT Sporty eSP K81"
insert_motorcycle "Honda" "BeAT dan BeAT Street K1A"
insert_motorcycle "Honda" "BeAT dan BeAT Street K1AL"
insert_motorcycle "Honda" "PCX 125 CBU"
insert_motorcycle "Honda" "PCX 150 CBU"
insert_motorcycle "Honda" "PCX 150 CBU K36J"
insert_motorcycle "Honda" "PCX 150 K97"
insert_motorcycle "Honda" "PCX 160 e:HEV"
insert_motorcycle "Honda" "PCX 160 K1Z"
insert_motorcycle "Honda" "PCX 160 New"
insert_motorcycle "Honda" "Scoopy eSP K16R"
insert_motorcycle "Honda" "Scoopy eSP K93"
insert_motorcycle "Honda" "Scoopy FI K16G"
insert_motorcycle "Honda" "Scoopy K2F"
insert_motorcycle "Honda" "Scoopy K2FP"
insert_motorcycle "Honda" "Scoopy Karburator KYT"
insert_motorcycle "Honda" "Vario 110 CW"
insert_motorcycle "Honda" "Vario 110 eSP"
insert_motorcycle "Honda" "Vario 110 FI"
insert_motorcycle "Honda" "Vario 110 Techno A"
insert_motorcycle "Honda" "Vario 110 Techno B"
insert_motorcycle "Honda" "Vario 125 eSP K2V"
insert_motorcycle "Honda" "Vario 125 eSP K60"
insert_motorcycle "Honda" "Vario 125 eSP K60R"
insert_motorcycle "Honda" "Vario 150 eSP K59"
insert_motorcycle "Honda" "Vario 150 eSP K59J"
insert_motorcycle "Honda" "Vario 160 K2S"
insert_motorcycle "Honda" "Vario Techno 125 FI CBS ISS"
insert_motorcycle "Honda" "Vario Techno 125 FI STD"
insert_motorcycle "Honda" "Vario Techno 125 Helm-In FI"
insert_motorcycle "Honda" "Vario Techno 125 Helm-In FI CBS"

echo "Inserting Manual Motorcycles..."
# Manual Motorcycles
insert_motorcycle "Honda" "Blade 110 K07A"
insert_motorcycle "Honda" "Blade 110 KWB"
insert_motorcycle "Honda" "Blade 110 S K07J"
insert_motorcycle "Honda" "Blade 125 FI K47"
insert_motorcycle "Honda" "Grand Impressa"
insert_motorcycle "Honda" "Karisma"
insert_motorcycle "Honda" "Legenda"
insert_motorcycle "Honda" "Mega Pro"
insert_motorcycle "Honda" "Mega Pro Advance"
insert_motorcycle "Honda" "Mega Pro FI"
insert_motorcycle "Honda" "Mega Pro New"
insert_motorcycle "Honda" "Revo"
insert_motorcycle "Honda" "Revo 110"
insert_motorcycle "Honda" "Revo 110 FI"
insert_motorcycle "Honda" "Revo 110 New"
insert_motorcycle "Honda" "Revo AT"
insert_motorcycle "Honda" "Supra"
insert_motorcycle "Honda" "Supra FIT"
insert_motorcycle "Honda" "Supra GTR K56F"
insert_motorcycle "Honda" "Supra GTR K56W"
insert_motorcycle "Honda" "Supra X 125"
insert_motorcycle "Honda" "Supra X 125 FI New"
insert_motorcycle "Honda" "Supra X 125 Helm-In FI"
insert_motorcycle "Honda" "Supra X 125 Helm-in Karburator"
insert_motorcycle "Honda" "Supra X 125 Injection"
insert_motorcycle "Honda" "Supra XX"
insert_motorcycle "Honda" "Tiger 2000"
insert_motorcycle "Honda" "Tiger Revolution A"
insert_motorcycle "Honda" "Tiger Revolution B"
insert_motorcycle "Honda" "Tiger Revolution C"
insert_motorcycle "Honda" "Verza 150"

echo "Inserting Sport Motorcycles..."
# Sport Motorcycles
insert_motorcycle "Honda" "ADV 150"
insert_motorcycle "Honda" "ADV 160"
insert_motorcycle "Honda" "CB150 Verza"
insert_motorcycle "Honda" "CB150R StreetFire K15"
insert_motorcycle "Honda" "CB150R StreetFire K15G"
insert_motorcycle "Honda" "CB150R StreetFire K15M"
insert_motorcycle "Honda" "CB150R StreetFire K15P"
insert_motorcycle "Honda" "CB150X"
insert_motorcycle "Honda" "CBR 150R CBU KPP"
insert_motorcycle "Honda" "CBR 150R K45A"
insert_motorcycle "Honda" "CBR 150R K45G"
insert_motorcycle "Honda" "CBR 150R K45N"
insert_motorcycle "Honda" "CBR 150R K45R"
insert_motorcycle "Honda" "CBR 250R K33A"
insert_motorcycle "Honda" "CBR 250R KYJ"
insert_motorcycle "Honda" "CBR 250RR K64"
insert_motorcycle "Honda" "CBR 250RR K64J"
insert_motorcycle "Honda" "CBR 250RR K64N"
insert_motorcycle "Honda" "CRF150L K84"
insert_motorcycle "Honda" "CRF250 Rally"
insert_motorcycle "Honda" "CS1 KWC"
insert_motorcycle "Honda" "Forza 250"
insert_motorcycle "Honda" "Sonic 150R K56"

echo "All Honda motorcycles have been inserted!" 